spring.application.name: junit-course
spring:
#  profiles:
#    active: dev
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver